### ISSUE TITLE
withPlugins (next-compose-plugins) support

### ISSUE THREAD

**Issue by kalabro** [tusbar/next-runtime-dotenv#54]
Thank you for a great plugin.

Is it possible to use it with withPlugins (https://github.com/cyrilwanner/next-compose-plugins). My initial attempt failed. 

Might be related: https://github.com/cyrilwanner/next-compose-plugins/issues/8

**Comment by tusbar** [comment]
I can’t see why it wouldn’t work.

Keep in mind that this plugin sort of exposes a next.js plugin factory (unlike next-sass that merges next options and its own options).

Untested but it would look something like this:

```js
const withPlugins = require('next-compose-plugins')
const nextRuntimeDotenv = require('next-runtime-dotenv')

const withConfig = nextRuntimeDotenv({
  public: [
    'MY_API_URL'
  ]
})

module.exports = withPlugins([
  [withConfig]
])
```

**Comment by kalabro** [comment]
@tusbar that is exactly what I tried. The app started just fine, but env variables were not exposed. Let me create a demo repo with my use case.

**Comment by kalabro** [comment]
Hi @tusbar! I just ran a quick test on top of create-next-app and it worked fine: 

```
const withPlugins = require('next-compose-plugins');
const nextRuntimeDotenv = require('next-runtime-dotenv');

const withConfig = nextRuntimeDotenv({
  public: [
    'MY_API_URL',
  ],
});

const nextConfig = {
  webpack: (config) => {
    // Fixes npm packages that depend on `fs` module.
    config.node = { // eslint-disable-line no-param-reassign
      fs: 'empty',
    };
    return config;
  },
};

module.exports = withConfig(withPlugins([
  [withConfig],
], nextConfig));
```

So it's something with my application that breaks next-runtime-dotenv. Closing the issue.

**Comment by kalabro** [comment]
Silly me, I wrapped `withPlugins` into `withConfig`, that's why it worked. Please find reproducible example here: https://github.com/kalabro/next-runtime-dotenv-with-plugins

```
[ ready ] compiled successfully
[ info ]  ready on http://localhost:3000
TypeError: Cannot read property 'MY_API_URL' of undefined
    at Module../pages/index.js (/Users/kalabro/DevEnv/www/next-runtime-dotenv-with-plugins/.next/server/static/development/pages/index.js:1710:49)
    at __webpack_require__ (/Users/kalabro/DevEnv/www/next-runtime-dotenv-with-plugins/.next/server/static/development/pages/index.js:23:31)
    at Object.3 (/Users/kalabro/DevEnv/www/next-runtime-dotenv-with-plugins/.next/server/static/development/pages/index.js:1878:18)
    at __webpack_require__ (/Users/kalabro/DevEnv/www/next-runtime-dotenv-with-plugins/.next/server/static/development/pages/index.js:23:31)
    at /Users/kalabro/DevEnv/www/next-runtime-dotenv-with-plugins/.next/server/static/development/pages/index.js:91:18
    at Object.<anonymous> (/Users/kalabro/DevEnv/www/next-runtime-dotenv-with-plugins/.next/server/static/development/pages/index.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at EventEmitter.handleCallback (/Users/kalabro/DevEnv/www/next-runtime-dotenv-with-plugins/node_modules/next/dist/server/on-demand-entry-handler.js:246:35)
    at Object.onceWrapper (events.js:273:13)
    at EventEmitter.emit (events.js:182:13)
```

**Comment by tusbar** [comment]
This is another issue: https://github.com/zeit/next.js/issues/7713

**Comment by tusbar** [comment]
@kalabro should be good now. :)
